### ISSUE TITLE
Bug: Error running rails db:setup on a fresh install

### ISSUE THREAD

**Issue by joelbrewer** [OWASP/railsgoat#370]
Running `rails db:setup` returns an error.

🐞 **Problem**

I performed a fresh clone, `bundle install`, and subsequent `rails db:setup` and received the following error: 

> rails aborted!
> FrozenError: can't modify frozen String: "railties_load_path="
> /Users/joelbrewer/Repos/railsgoat/config/application.rb:4:in `require'
> /Users/joelbrewer/Repos/railsgoat/config/application.rb:4:in `<top (required)>'
> /Users/joelbrewer/Repos/railsgoat/Rakefile:5:in `require_relative'
> /Users/joelbrewer/Repos/railsgoat/Rakefile:5:in `<top (required)>'
> script/rails:7:in `require'
> script/rails:7:in `<main>'

Steps to reproduce:

- `git clone`
- `bundle install`
- `rails db:setup`

💡 **Possible solutions**

I have a feeling this could be a ruby/rails version issue (I noticed the Ruby version was recently upgraded).

**Comment by jasnow** [comment]
What version of ruby are you using?

**Comment by joelbrewer** [comment]
![image](https://user-images.githubusercontent.com/2348386/66862981-4c1dff80-ef4f-11e9-947c-e1094770382b.png)

Using rbenv -- this was the only 2.7.0 version available.

**Comment by jasnow** [comment]
I use rvm with .rvmrc: rvm use 2.7.0-preview1@ruby2.7-rails6.0 --create

**Comment by joelbrewer** [comment]
Got it - I'll try using `rvm` 👍

**Comment by treprime** [comment]
Any update on.  This has been a nightmare to install on a fresh ubuntu instance and docker.

**Comment by cktricky** [comment]
@treprime are you using RVM as noted above?

**Comment by treprime** [comment]
@cktricky  I managed to get it working.  Steps below

-  Install ruby and ruby-build

        sudo apt-get install ruby \
        ruby-build -y

- Install mysql

        sudo apt-get install mysql-server \
        mysql-client \
        libmysqlclient-dev

- Install rvm (ruby version manager)

        curl -sSL https://get.rvm.io | bash -s stable

- source the directory

        source ~/.rvm/scripts/rvm

- Install the bundler

        gem install bundler

- install the required version of ruby for the project
                
        rvm install bundler:2.1.0.pre.1

- Clone railsgoat
        
        git clone https://github.com/OWASP/railsgoat.git
        cd railsgoat

- Install ruby 2.7 preview

        rvm install "ruby-2.7.0-preview1"
        
- Install the bundles
        
        bundle install

- Setup the database

        bundle exec rake db:setup

- Start the server

        bundle exec rails server

- Open a browser and navigate to http://localhost:3000

**Comment by cktricky** [comment]
Thank you @tre-island. I think I need to try and build this on a fresh ubuntu install to see what we could improve on our end.
